export const SEARCH_FOCUS ='header/SEARCH_FOCUS'
export const SEARCH_BLUR ='header/SEARCH_BLUR'
export const CHANGE_LIST = 'header/CHANGE_LIST'
export const HANDLE_ENTER='header/HANDLE_ENTER'
export const HANDLE_LEAVE ='header/HANDLE_LEAVE'
export const HANDEL_PAGE = 'header/HANDEL_PAGE'